Timestamp,Operator,URL,Issue
2023-06-21T07:57:49.948018+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Carte_de_danger___Glissements_de_terrain/MapServer/WFSServer?request=GetCapabilities&service=WFS,"GET requested yielded HTTP response status code 499"
2023-06-21T07:59:39.820114+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Cultures/MapServer/WFSServer?request=GetCapabilities&service=WFS,"GET requested yielded HTTP response status code 499"
2023-06-21T08:06:55.688485+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Prairies_et_paturages_secs_d_importance_cantonale/MapServer/WFSServer?request=GetCapabilities&service=WFS,"GET requested yielded HTTP response status code 499"
2023-06-21T08:06:56.262295+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Prairies_et_paturages_secs_d_importance_nationale/MapServer/WFSServer?request=GetCapabilities&service=WFS,"GET requested yielded HTTP response status code 499"
2023-06-21T08:07:27.634035+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Proportion_du_bati_expose_aux_dangers_naturels_par_commune/MapServer/WFSServer?request=GetCapabilities&service=WFS,"Service does not seem to be a valid WMS, WMTS or WFS"
2023-06-21T08:07:28.754327+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Qualite_des_donnees_descriptives/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Qualite_des_donnees_descriptives/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6cf340>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:29.879615+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Qualite_des_immeubles_en_vigueur/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Qualite_des_immeubles_en_vigueur/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ecf4c940>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:31.000155+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Qualite_des_immeubles_projetes/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Qualite_des_immeubles_projetes/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ebc6d850>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:31.104307+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Reducteurs_AquaFri/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Reducteurs_AquaFri/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ecf4cf40>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:31.203265+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Remaniements_parcellaires/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Remaniements_parcellaires/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ecf4c0a0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:31.301688+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Repartition_des_niveaux_de_tolerance/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Repartition_des_niveaux_de_tolerance/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6cf910>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:31.398800+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Repartitions_des_plans/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Repartitions_des_plans/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6e2cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:31.497586+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Reseau_d_itineraires_en_zones_de_tranquillite/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Reseau_d_itineraires_en_zones_de_tranquillite/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6e26d0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:31.597022+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Reseaux_ecologiques/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Reseaux_ecologiques/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ebc6df10>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:31.696093+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Reseaux_integres_dans_AquaFri/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Reseaux_integres_dans_AquaFri/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6e2730>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:31.801645+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Reseaux_non_integres_dans_AquaFri/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Reseaux_non_integres_dans_AquaFri/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ed311a60>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:31.906751+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Reserve_mycologique/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Reserve_mycologique/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6cf550>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:32.009783+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Reserves_d_oiseaux_d_eau_et_migrateurs/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Reserves_d_oiseaux_d_eau_et_migrateurs/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ebc6d520>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:32.108966+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Reserves_de_faune_pour_la_chasse/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Reserves_de_faune_pour_la_chasse/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ecf4c340>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:32.212412+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Reserves_forestieres_cantonales/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Reserves_forestieres_cantonales/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ecf4cb20>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:32.313967+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Reserves_forestieres_RDPPF/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Reserves_forestieres_RDPPF/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6cfee0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:32.424253+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Reserves_forestieres/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Reserves_forestieres/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ebc6d2e0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:32.526022+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Reserves_naturelles_cantonales/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Reserves_naturelles_cantonales/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ebc6d730>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:32.637300+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Reserves_paysageres_cantonales/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Reserves_paysageres_cantonales/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6e2dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:32.740232+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Reservoirs_AquaFri/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Reservoirs_AquaFri/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6e28e0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:32.847732+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Ressources___sources_et_puits___de_l_inventaire_des_eaux_souterraines/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Ressources___sources_et_puits___de_l_inventaire_des_eaux_souterraines/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ecf4c310>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:32.952172+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Revetements_phono_absorbants_routes_cantonales/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Revetements_phono_absorbants_routes_cantonales/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6e2970>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:33.053625+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Revision_generale_PAL_amenagement_local/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Revision_generale_PAL_amenagement_local/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ebc6d220>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:33.160511+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Routes_Cantonales_ORGT___OUMin/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Routes_Cantonales_ORGT___OUMin/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ebc6db50>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:33.265582+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Routes_Cantonales_OSR/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Routes_Cantonales_OSR/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ecf4ccd0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:33.366509+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Routes_lineaires_OPAM/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Routes_lineaires_OPAM/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6cfc70>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:33.469743+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Routes_Nationales/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Routes_Nationales/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6cf5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:33.568009+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Routes_surfaciques_OPAM/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Routes_surfaciques_OPAM/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ebc6d8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:33.667944+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Ruisseaux_utilises_par_l_Etat/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Ruisseaux_utilises_par_l_Etat/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ecf4c340>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:33.766589+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Salamandre_tachetee/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Salamandre_tachetee/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ecf4ca30>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:33.868147+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Secteur_de_dangers_naturels_RDPPF_affectation/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Secteur_de_dangers_naturels_RDPPF_affectation/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6e2430>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:33.966339+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Secteurs_a_objectifs_de_protection_du_patrimoine_PAL/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Secteurs_a_objectifs_de_protection_du_patrimoine_PAL/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6cf8b0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:34.067253+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Secteurs_de_faune/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Secteurs_de_faune/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ecb9be20>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:34.167373+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Secteurs_de_protection_du_patrimoine_ayant_passe_l_enquete_publique_PAL_en_revison/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Secteurs_de_protection_du_patrimoine_ayant_passe_l_enquete_publique_PAL_en_revison/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6e2e50>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:34.265179+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Secteurs_soumis_a_PAD_amenagement_local/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Secteurs_soumis_a_PAD_amenagement_local/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ecf4cf10>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:34.368095+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Servitudes_Labels/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Servitudes_Labels/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6ec4f0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:34.469259+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Servitudes_Lignes/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Servitudes_Lignes/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ebc6d3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:34.567921+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Servitudes_Points/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Servitudes_Points/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ecb9bf40>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:34.666729+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Servitudes_Surfaces/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Servitudes_Surfaces/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ebc6d850>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:34.767355+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Sirenes_de_la_PCi/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Sirenes_de_la_PCi/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ebc6df70>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:34.866318+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Sites_a_batraciens_annexe_1/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Sites_a_batraciens_annexe_1/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ecf4c130>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:34.966314+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Sites_a_batraciens_annexe_2/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Sites_a_batraciens_annexe_2/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6e2cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:35.069442+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Sites_a_batraciens_annexe_3/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Sites_a_batraciens_annexe_3/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6e2790>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:35.166118+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Sites_a_batraciens_objets_fixes/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Sites_a_batraciens_objets_fixes/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ecb9b7f0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:35.271056+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Sites_a_batraciens_objets_itinerants/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Sites_a_batraciens_objets_itinerants/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6e2f40>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:35.373531+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Sites_bases_sur_l_ISOS/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Sites_bases_sur_l_ISOS/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ecf4cd30>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:35.476804+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Sites_de_reproduction_de_batraciens_d_importance_locale/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Sites_de_reproduction_de_batraciens_d_importance_locale/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ecf4cfd0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:35.575885+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Sites_marecageux_d_importance_nationale/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Sites_marecageux_d_importance_nationale/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ecb9bfa0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:35.676559+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Sites_prioritaires_prairies_et_paturages_secs/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Sites_prioritaires_prairies_et_paturages_secs/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ebc6d190>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:35.780373+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Stations_d_epuration/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Stations_d_epuration/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ebc6d550>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:35.884130+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Stations_de_fecondation_des_abeilles/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Stations_de_fecondation_des_abeilles/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ebc6d820>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:35.987442+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Stations_forestieres/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Stations_forestieres/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ed311b50>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:36.091100+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Stations_meteo_degres_jours_et_temperatures_moyennes/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Stations_meteo_degres_jours_et_temperatures_moyennes/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6e2400>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:36.194948+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Statuts_des_donnees_descriptives/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Statuts_des_donnees_descriptives/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ecb9ba90>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:36.297734+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Statuts_des_immeubles_en_vigueur/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Statuts_des_immeubles_en_vigueur/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6cfcd0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:36.402669+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Statuts_des_immeubles_projetes/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Statuts_des_immeubles_projetes/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6cf880>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:36.515223+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Structures_d_accueil/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Structures_d_accueil/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ecb9bd30>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:36.618617+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Structures_d_activites_de_promotion_enfance_jeunesse/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Structures_d_activites_de_promotion_enfance_jeunesse/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6e2700>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:36.715676+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Surface_agricole_utile/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Surface_agricole_utile/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6e27f0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:36.818169+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Surface_chaussee_routes_cantonales/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Surface_chaussee_routes_cantonales/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6cf3a0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:36.917557+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Surface_de_couverture_Sirenes_de_la_PCi/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Surface_de_couverture_Sirenes_de_la_PCi/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ebc6d760>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:37.017566+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Surfaces_a_aptitude_reduite_pour_la_culture_des_champs/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Surfaces_a_aptitude_reduite_pour_la_culture_des_champs/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ebc6dd90>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:37.120182+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Surfaces_d_assolement/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Surfaces_d_assolement/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ebc6d9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:37.218960+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Surfaces_de_promotion_de_la_biodiversite_SPB_I/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Surfaces_de_promotion_de_la_biodiversite_SPB_I/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ed3110d0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:37.318556+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Surfaces_de_promotion_de_la_biodiversite_SPB_II_Estivage/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Surfaces_de_promotion_de_la_biodiversite_SPB_II_Estivage/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6e2910>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:37.416808+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Surfaces_de_promotion_de_la_biodiversite_SPB_II_Plaine/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Surfaces_de_promotion_de_la_biodiversite_SPB_II_Plaine/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6cf9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:37.518129+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Syndicats_de_chemins_alpestres/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Syndicats_de_chemins_alpestres/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ecb9b8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:37.617246+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Talus_a_valeur_ecologique_routes_cantonales/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Talus_a_valeur_ecologique_routes_cantonales/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ecb9be80>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:37.718992+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Terrains_en_pente/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Terrains_en_pente/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ecb9be20>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:37.821917+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Territoires_de_chasse_en_montagne/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Territoires_de_chasse_en_montagne/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6cf880>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:37.923900+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Trafic_journalier_moyen/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Trafic_journalier_moyen/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6e2550>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:38.038581+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Trafic_poids_lourds/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Trafic_poids_lourds/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6e2df0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:38.140499+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Triages_forestiers/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Triages_forestiers/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ebc6dcd0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:38.245303+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Troncons_de_rues_en_couleurs/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Troncons_de_rues_en_couleurs/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ebc6da90>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:38.351003+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Troncons_de_rues/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Troncons_de_rues/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ebc6d790>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:38.456134+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Type_d_objet_ISOS___Ligne/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Type_d_objet_ISOS___Ligne/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ed311a90>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:38.559850+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Type_d_objet_ISOS___Polygone/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Type_d_objet_ISOS___Polygone/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6e2520>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:38.669978+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Unites_d_exploitation/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Unites_d_exploitation/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6cf340>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:38.772190+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Unites_de_gestion_des_forets_publiques/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Unites_de_gestion_des_forets_publiques/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ecb9bd90>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:38.869241+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Unites_pastorales_catholiques/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Unites_pastorales_catholiques/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ecb9b4f0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:38.979598+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Vannes_AquaFri/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Vannes_AquaFri/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ecb9b730>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:39.080759+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Vigne_en_production_AOC/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Vigne_en_production_AOC/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6cf400>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:39.182177+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Vignobles_en_pente/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Vignobles_en_pente/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6e2430>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:39.281284+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Voies_historiques_IVS/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Voies_historiques_IVS/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6e2910>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:39.382839+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Zones_a_batir_et_perimetre_d_habitat_a_maintenir_amenagement_local_PAZ/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Zones_a_batir_et_perimetre_d_habitat_a_maintenir_amenagement_local_PAZ/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ebc6d760>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:39.484879+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Zones_alluviales_d_importance_locale/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Zones_alluviales_d_importance_locale/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ebc6db80>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:39.587109+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Zones_alluviales_d_importance_nationale/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Zones_alluviales_d_importance_nationale/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ebc6dc40>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:39.692368+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Zones_alluviales/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Zones_alluviales/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ed311b50>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:39.793659+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Zones_de_contribution_federale_MO/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Zones_de_contribution_federale_MO/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6e2b20>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:39.895684+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Zones_de_desserte_de_l_approvisionnement_en_electricite/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Zones_de_desserte_de_l_approvisionnement_en_electricite/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6cfa00>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:40.008091+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Zones_de_protection_des_eaux_souterraines_RDPPF/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Zones_de_protection_des_eaux_souterraines_RDPPF/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ecb9b7c0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:40.109071+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Zones_de_recrutement_des_etablissements_primaires_francophones/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Zones_de_recrutement_des_etablissements_primaires_francophones/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ecb9be20>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:40.209429+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Zones_de_recrutement_des_etablissements_primaires_germanophones/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Zones_de_recrutement_des_etablissements_primaires_germanophones/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ecb9bdc0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:40.306173+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Zones_de_recrutement_des_etablissements_secondaires_francophones/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Zones_de_recrutement_des_etablissements_secondaires_francophones/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6cf040>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:07:40.411802+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Zones_de_recrutement_des_etablissements_secondaires_germanophones/MapServer/WFSServer?request=GetCapabilities&service=WFS,"HTTPSConnectionPool(host='geo.fr.ch', port=443): Max retries exceeded with url: /ags/services/OpenData/Zones_de_recrutement_des_etablissements_secondaires_germanophones/MapServer/WFSServer?request=GetCapabilities&service=WFS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1ec6e29a0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2023-06-21T08:10:29.856231+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Carte_de_danger___Chutes_de_pierres___blocs/MapServer/WMSServer?request=GetCapabilities&service=WMS,"GET requested yielded HTTP response status code 499"
2023-06-21T08:10:38.116646+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Carte_de_danger___Glissements_de_terrain/MapServer/WMSServer?request=GetCapabilities&service=WMS,"GET requested yielded HTTP response status code 499"
2023-06-21T08:12:20.201991+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Cultures/MapServer/WMSServer?request=GetCapabilities&service=WMS,"GET requested yielded HTTP response status code 499"
2023-06-21T08:16:04.802368+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Limite_du_canton/MapServer/WMSServer?request=GetCapabilities&service=WMS,"'NoneType' object has no attribute 'identification'"
2023-06-21T08:18:48.897617+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Prairies_et_paturages_secs_d_importance_cantonale/MapServer/WMSServer?request=GetCapabilities&service=WMS,"GET requested yielded HTTP response status code 499"
2023-06-21T08:18:49.371640+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Prairies_et_paturages_secs_d_importance_nationale/MapServer/WMSServer?request=GetCapabilities&service=WMS,"GET requested yielded HTTP response status code 499"
2023-06-21T08:20:14.726745+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Routes_Cantonales_LR/MapServer/WMSServer?request=GetCapabilities&service=WMS,"GET requested yielded HTTP response status code 499"
2023-06-21T08:22:39.605214+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Sites_a_batraciens_annexe_1/MapServer/WMSServer?request=GetCapabilities&service=WMS,"GET requested yielded HTTP response status code 499"
2023-06-21T08:22:40.094984+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Sites_a_batraciens_annexe_2/MapServer/WMSServer?request=GetCapabilities&service=WMS,"GET requested yielded HTTP response status code 499"
2023-06-21T08:22:40.578642+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Sites_a_batraciens_annexe_3/MapServer/WMSServer?request=GetCapabilities&service=WMS,"GET requested yielded HTTP response status code 499"
2023-06-21T08:22:41.135176+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Sites_a_batraciens_objets_fixes/MapServer/WMSServer?request=GetCapabilities&service=WMS,"GET requested yielded HTTP response status code 499"
2023-06-21T08:22:41.608983+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Sites_a_batraciens_objets_itinerants/MapServer/WMSServer?request=GetCapabilities&service=WMS,"GET requested yielded HTTP response status code 499"
2023-06-21T08:23:51.997343+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Surface_agricole_utile/MapServer/WMSServer?request=GetCapabilities&service=WMS,"GET requested yielded HTTP response status code 499"
2023-06-21T08:25:01.401265+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Zones_a_batir_et_perimetre_d_habitat_a_maintenir_amenagement_local_PAZ/MapServer/WMSServer?request=GetCapabilities&service=WMS,"GET requested yielded HTTP response status code 499"
2023-06-21T08:25:48.556243+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData/Zones_reservees_routes_cantonales/MapServer/WMSServer?request=GetCapabilities&service=WMS,"GET requested yielded HTTP response status code 499"
2023-06-21T08:27:10.121791+02:00,KT_FR,https://geo.fr.ch/ags/services/OpenData_Raster/CN500/MapServer/WMSServer?request=GetCapabilities&service=WMS,"'NoneType' object has no attribute 'identification'"
